[{"\u00e9quipe": "040", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 74, in <module>\n    main()\n  File \"projet1.py\", line 40, in main\n    liste.append((d_debut, response['Time Series (Daily)'][d_debut][dic[mode]]))\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "042", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v,--valeur {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: -v=volume\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "043", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  usage: projet1.py [-h] [-start DATE] [-end DATE]\n                  [-value {fermeture, ouverture, min, max, volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: -v=volume -d=2018-09-21 -f=2018-09-24\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "044", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "045", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    nouveau_dico = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "046", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "047", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 94, in <module>\n    donn\u00e9es(DEBUT, FIN)\n  File \"projet1.py\", line 80, in donn\u00e9es\n    don = RESPONSE['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "048", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 20, in <module>\n    print('{}({}, {}, {}'.format(args.symboles, args.v, args.f, args.d))\nAttributeError: 'Namespace' object has no attribute 'v'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "049", "score": 70, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 105, in <module>\n    calcul_boursier(ARGS.symbole)\n  File \"projet1.py\", line 98, in calcul_boursier\n    tuple1 = (str(DEBUT), response['Time Series (Daily)'][str(DEBUT)][str(variable)])\nKeyError: '2018-11-24'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --fin=2018-09-24\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 105, in <module>\n    calcul_boursier(ARGS.symbole)\n  File \"projet1.py\", line 98, in calcul_boursier\n    tuple1 = (str(DEBUT), response['Time Series (Daily)'][str(DEBUT)][str(variable)])\nKeyError: '2018-11-24'\n\n\n</pre>"}, {"\u00e9quipe": "050", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog (fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog (fermeture, 2018-11-24, 2018-11-24)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 84, in <module>\n    [DATE_DEBUT.strftime('%Y-%m-%d')]\nKeyError: '2018-11-24'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DEBUT] [-f FIN]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog (volume, 2018-11-24, 2018-11-24)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 84, in <module>\n    [DATE_DEBUT.strftime('%Y-%m-%d')]\nKeyError: '2018-11-24'\n\n\n</pre>"}, {"\u00e9quipe": "051", "score": 74, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog (fermeture, 2018-07-24, 2018-09-24)', \"[('2018-09-24', '1173.3700'), ('2018-09-21', '1166.0900'), ('2018-09-20', '1186.8700'), ('2018-09-19', '1171.0900'), ('2018-09-18', '1161.2200'), ('2018-09-17', '1156.0500'), ('2018-09-14', '1172.5300'), ('2018-09-13', '1175.3300'), ('2018-09-12', '1162.8200'), ('2018-09-11', '1177.3600'), ('2018-09-10', '1164.6400'), ('2018-09-07', '1164.8300'), ('2018-09-06', '1171.4400'), ('2018-09-05', '1186.4800'), ('2018-09-04', '1197.0000'), ('2018-08-31', '1218.1900'), ('2018-08-30', '1239.1200'), ('2018-08-29', '1249.3000'), ('2018-08-28', '1231.1500'), ('2018-08-27', '1241.8200'), ('2018-08-24', '1220.6500'), ('2018-08-23', '1205.3800'), ('2018-08-22', '1207.3300'), ('2018-08-21', '1201.6200'), ('2018-08-20', '1207.7700'), ('2018-08-17', '1200.9600'), ('2018-08-16', '1206.4900'), ('2018-08-15', '1214.3800'), ('2018-08-14', '1242.1000'), ('2018-08-13', '1235.0100'), ('2018-08-10', '1237.6100'), ('2018-08-09', '1249.1000'), ('2018-08-08', '1245.6100'), ('2018-08-07', '1242.2200'), ('2018-08-06', '1224.7700'), ('2018-08-03', '1223.7100'), ('2018-08-02', '1226.1500'), ('2018-08-01', '1220.0100'), ('2018-07-31', '1217.2600'), ('2018-07-30', '1219.7400'), ('2018-07-27', '1238.5000'), ('2018-07-26', '1268.3300'), ('2018-07-25', '1263.7000'), ('2018-07-24', '1248.0800')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Seulement 5 titres boursier peuvent \u00ebtre analys\u00e9s par minute\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,volume,min,max,ouverture}]\n                  Symbole [Symbole ...]\nProjet1.py: error: unrecognized arguments: --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog (volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Seulement 5 titres boursier peuvent \u00ebtre analys\u00e9s par minute\n\n\n</pre>"}, {"\u00e9quipe": "052", "score": 79, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 111, in <module>\n    affichage_final(ARGS.symbole, ARGS.d\u00e9but, ARGS.fin, ARGS.valeur)\n  File \"projet1.py\", line 104, in affichage_final\n    afficher_ieme_symbole(symbole, debut, fin, valeur)\n  File \"projet1.py\", line 90, in afficher_ieme_symbole\n    for key, value in dict_titre_boursier(debut, symbole)[\"Time Series (Daily)\"].items():\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "053", "score": 100, "commentaires": ""}, {"\u00e9quipe": "054", "score": 87, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-26', '1268.3300'), ('2018-07-30', '1219.7400'), ('2018-08-01', '1220.0100'), ('2018-08-03', '1223.7100'), ('2018-08-07', '1242.2200'), ('2018-08-09', '1249.1000'), ('2018-08-13', '1235.0100'), ('2018-08-15', '1214.3800'), ('2018-08-17', '1200.9600'), ('2018-08-21', '1201.6200'), ('2018-08-23', '1205.3800'), ('2018-08-27', '1241.8200'), ('2018-08-29', '1249.3000'), ('2018-08-31', '1218.1900'), ('2018-09-05', '1186.4800'), ('2018-09-07', '1164.8300'), ('2018-09-11', '1177.3600'), ('2018-09-13', '1175.3300'), ('2018-09-17', '1156.0500'), ('2018-09-19', '1171.0900'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700'), ('2018-09-20', '1186.8700'), ('2018-09-18', '1161.2200'), ('2018-09-14', '1172.5300'), ('2018-09-12', '1162.8200'), ('2018-09-10', '1164.6400'), ('2018-09-06', '1171.4400'), ('2018-09-04', '1197.0000'), ('2018-08-30', '1239.1200'), ('2018-08-28', '1231.1500'), ('2018-08-24', '1220.6500'), ('2018-08-22', '1207.3300'), ('2018-08-20', '1207.7700'), ('2018-08-16', '1206.4900'), ('2018-08-14', '1242.1000'), ('2018-08-10', '1237.6100'), ('2018-08-08', '1245.6100'), ('2018-08-06', '1224.7700'), ('2018-08-02', '1226.1500'), ('2018-07-31', '1217.2600'), ('2018-07-27', '1238.5000'), ('2018-07-25', '1263.7000')]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog,aapl(volume, 2018-11-24, 2018-11-24)']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 125, in <module>\n    main()\n  File \"projet1.py\", line 120, in main\n    res = traitment_donnee(req, arg)\n  File \"projet1.py\", line 90, in traitment_donnee\n    for cle_date_requete in reponse_api['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "055", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 86, in <module>\n    affichage(donnees(DEBUT, FIN, b), DATES, VALEUR)\n  File \"projet1.py\", line 71, in affichage\n    if dico['Time Series (Daily)'].get(i) is not None:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "056", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "057", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "058", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "059", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 106, in <module>\n    afficherfinal(ARGS.symbole, ARGS.valeur, ARGS.d\u00e9but, ARGS.fin)\n  File \"Projet1.py\", line 99, in afficherfinal\n    afficherlisteval(symbole, valeur, debut, fin)\n  File \"Projet1.py\", line 85, in afficherlisteval\n    for i, value in dictvaleurs(symbole, 'compact')['Time Series (Daily)'].items():\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "060", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "061", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :    File \"projet1.py\", line 34\n    import argparse\n         ^\nIndentationError: expected an indented block\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "062", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 124, in <module>\n    sortie(d\u00e9but, fin, alphavantage(x))\n  File \"Projet1.py\", line 112, in sortie\n    if str(ddate) in response['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "063", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\n\n</pre>"}, {"\u00e9quipe": "064", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 75, in <module>\n    affichage(ARGS.symbole, ARGS.valeur, ARGS.d\u00e9but, ARGS.fin)\n  File \"Projet1.py\", line 69, in affichage\n    liste = list(tuple((datedebut, response['Time Series (Daily)'][datedebut][vd])))\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "066", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 100, in <module>\n    main()\n  File \"projet1.py\", line 51, in main\n    data['Time Series (Daily)'],\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}]