[{"\u00e9quipe": "163", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :    File \"projet1.py\", line 62\n    def affichage:\n                 ^\nSyntaxError: invalid syntax\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "184", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :    File \"projet1.py\", line 52\n    return reponse\n    ^\nSyntaxError: 'return' outside function\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "144", "score": 78, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 92, in <module>\n    print([(str(DATE_DEBUT), LISTE_VALEURS[0])])\nIndexError: list index out of range\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 92, in <module>\n    print([(str(DATE_DEBUT), LISTE_VALEURS[0])])\nIndexError: list index out of range\n\n\n</pre>"}, {"\u00e9quipe": "145", "score": 98, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "146", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "147", "score": 79, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 109, in <module>\n    if response['Time Series (Daily)'].get(a) is not None:\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\n\n</pre>"}, {"\u00e9quipe": "148", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-07-24, 2018-09-24)\", \"[('2018-07-24', '1248.0800'), ('2018-07-26', '1268.3300'), ('2018-07-30', '1219.7400'), ('2018-08-01', '1220.0100'), ('2018-08-03', '1223.7100'), ('2018-08-07', '1242.2200'), ('2018-08-09', '1249.1000'), ('2018-08-13', '1235.0100'), ('2018-08-15', '1214.3800'), ('2018-08-17', '1200.9600'), ('2018-08-21', '1201.6200'), ('2018-08-23', '1205.3800'), ('2018-08-27', '1241.8200'), ('2018-08-29', '1249.3000'), ('2018-08-31', '1218.1900'), ('2018-09-05', '1186.4800'), ('2018-09-07', '1164.8300'), ('2018-09-11', '1177.3600'), ('2018-09-13', '1175.3300'), ('2018-09-17', '1156.0500'), ('2018-09-19', '1171.0900'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700'), ('2018-09-20', '1186.8700'), ('2018-09-18', '1161.2200'), ('2018-09-14', '1172.5300'), ('2018-09-12', '1162.8200'), ('2018-09-10', '1164.6400'), ('2018-09-06', '1171.4400'), ('2018-09-04', '1197.0000'), ('2018-08-30', '1239.1200'), ('2018-08-28', '1231.1500'), ('2018-08-24', '1220.6500'), ('2018-08-22', '1207.3300'), ('2018-08-20', '1207.7700'), ('2018-08-16', '1206.4900'), ('2018-08-14', '1242.1000'), ('2018-08-10', '1237.6100'), ('2018-08-08', '1245.6100'), ('2018-08-06', '1224.7700'), ('2018-08-02', '1226.1500'), ('2018-07-31', '1217.2600'), ('2018-07-27', '1238.5000'), ('2018-07-25', '1263.7000')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-11-24, 2018-11-24)\", '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog', 'aapl'](volume, 2018-11-24, 2018-11-24)\", '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 72, in <module>\n    print(bourse(i, args.valeur, args.debut, args.fin))\n  File \"projet1.py\", line 55, in bourse\n    for date in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "149", "score": 69, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', 1248.0800), ('2018-07-25', 1263.7000), ('2018-07-26', 1268.3300), ('2018-07-27', 1238.5000), ('2018-07-30', 1219.7400), ('2018-07-31', 1217.2600), ('2018-08-01', 1220.0100), ('2018-08-02', 1226.1500), ('2018-08-03', 1223.7100), ('2018-08-06', 1224.7700), ('2018-08-07', 1242.2200), ('2018-08-08', 1245.6100), ('2018-08-09', 1249.1000), ('2018-08-10', 1237.6100), ('2018-08-13', 1235.0100), ('2018-08-14', 1242.1000), ('2018-08-15', 1214.3800), ('2018-08-16', 1206.4900), ('2018-08-17', 1200.9600), ('2018-08-20', 1207.7700), ('2018-08-21', 1201.6200), ('2018-08-22', 1207.3300), ('2018-08-23', 1205.3800), ('2018-08-24', 1220.6500), ('2018-08-27', 1241.8200), ('2018-08-28', 1231.1500), ('2018-08-29', 1249.3000), ('2018-08-30', 1239.1200), ('2018-08-31', 1218.1900), ('2018-09-04', 1197.0000), ('2018-09-05', 1186.4800), ('2018-09-06', 1171.4400), ('2018-09-07', 1164.8300), ('2018-09-10', 1164.6400), ('2018-09-11', 1177.3600), ('2018-09-12', 1162.8200), ('2018-09-13', 1175.3300), ('2018-09-14', 1172.5300), ('2018-09-17', 1156.0500), ('2018-09-18', 1161.2200), ('2018-09-19', 1171.0900), ('2018-09-20', 1186.8700), ('2018-09-21', 1166.0900), ('2018-09-24', 1173.3700)]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "150", "score": 79, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "151", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture, ouverture, min, max, volume} valeur]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: -v=volume\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "152", "score": 58, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"goog(['fermeture'], 2018-07-24, 2018-09-24)\", \"Le march\u00e9 boursier n'a pas de donn\u00e9es au moins une des journ\u00e9es sp\u00e9cifi\u00e9s,ou il y a eu plus de 5 requ\u00e8tes dans la derni\u00e8re minute.\", 'Changer les dates ou attendre pour avoir un r\u00e9sultat valide.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n [\"goog(['fermeture'], 2018-11-24, 2018-11-24)\", \"Le march\u00e9 boursier n'a pas de donn\u00e9es au moins une des journ\u00e9es sp\u00e9cifi\u00e9s,ou il y a eu plus de 5 requ\u00e8tes dans la derni\u00e8re minute.\", 'Changer les dates ou attendre pour avoir un r\u00e9sultat valide.']\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {ouverture, fermeture, min, max, volume} [{ouverture, fermeture, min, max, volume} ...]]\n                  symbole [symbole ...]\nProjet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {ouverture, fermeture, min, max, volume} [{ouverture, fermeture, min, max, volume} ...]]\n                  symbole [symbole ...]\nProjet1.py: error: argument -v/--valeur: invalid choice: 'goog' (choose from 'ouverture', 'fermeture', 'min', 'max', 'volume')\n\n\n</pre>"}, {"\u00e9quipe": "153", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "154", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "155", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24) ', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24) ', '[]']\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24) ', '[]', 'aapl(volume, 2018-11-24, 2018-11-24) ', '[]']\n\n</pre>"}, {"\u00e9quipe": "157", "score": 97, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\n\n</pre>"}, {"\u00e9quipe": "159", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture,2018-07-24,2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture,2018-11-24,2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume,2018-11-24,2018-11-24)', '[]', 'aapl(volume,2018-11-24,2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "161", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 66, in <module>\n    openD = response['Time Series (Daily)'][debut]['1. open']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "162", "score": 66, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 39, in <module>\n    ARGS.DATE = [ARGS.DATE[0], ARGS.DATE[0]] if len(ARGS.DATE) == 1 else ARGS.DATE\nTypeError: object of type 'NoneType' has no len()\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-24, 2018-09-21)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 39, in <module>\n    ARGS.DATE = [ARGS.DATE[0], ARGS.DATE[0]] if len(ARGS.DATE) == 1 else ARGS.DATE\nTypeError: object of type 'NoneType' has no len()\n\n\n</pre>"}, {"\u00e9quipe": "164", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 106, in <module>\n    formaterreponse(symbol, REPONSE, VALEUR, ARGS)\n  File \"projet1.py\", line 88, in formaterreponse\n    deuxiemeligne.append((datestr, response['Time Series (Daily)'][datestr][valeur]))\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "166", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 112, in <module>\n    if (str(date1) in response['Time Series (Daily)']) is True:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "167", "score": 62, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['2018-09-24', '2018-07-24', '62', 'compact', \"['2018-07-24', '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28', '2018-07-29', '2018-07-30', '2018-07-31', '2018-08-01', '2018-08-02', '2018-08-03', '2018-08-04', '2018-08-05', '2018-08-06', '2018-08-07', '2018-08-08', '2018-08-09', '2018-08-10', '2018-08-11', '2018-08-12', '2018-08-13', '2018-08-14', '2018-08-15', '2018-08-16', '2018-08-17', '2018-08-18', '2018-08-19', '2018-08-20', '2018-08-21', '2018-08-22', '2018-08-23', '2018-08-24', '2018-08-25', '2018-08-26', '2018-08-27', '2018-08-28', '2018-08-29', '2018-08-30', '2018-08-31', '2018-09-01', '2018-09-02', '2018-09-03', '2018-09-04', '2018-09-05', '2018-09-06', '2018-09-07', '2018-09-08', '2018-09-09', '2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16', '2018-09-17', '2018-09-18', '2018-09-19', '2018-09-20', '2018-09-21', '2018-09-22', '2018-09-23', '2018-09-24']\", '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['2018-11-24', '2018-11-24', '0', 'compact', \"['2018-11-24']\", '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture, ouverture, min, max, volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['2018-11-24', '2018-11-24', '0', 'compact', \"['2018-11-24']\", '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "168", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "169", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "170", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 84, in <module>\n    REP = parametre(i)\n  File \"projet1.py\", line 79, in parametre\n    rep_demand = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "171", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 11, in <module>\n    import pandas as  pd\nModuleNotFoundError: No module named 'pandas'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "172", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 85, in <module>\n    sortie(OUVRE, FERME, SYMBOL)\n  File \"projet1.py\", line 65, in sortie\n    if str(listedate) in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "173", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :    File \"Projet1.py\", line 69\n    elif args.valeur == 'volume'\n                               ^\nSyntaxError: invalid syntax\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "174", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :    File \"projet1.py\", line 41\n    for s in date.(\"-\"):\n                  ^\nSyntaxError: invalid syntax\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "175", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "178", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 79, in <module>\n    AFF = RESPONSE['Time Series (Daily)']['{}'.format(DATE)]\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "179", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 70, in <module>\n    valeurjours()\n  File \"projet1.py\", line 62, in valeurjours\n    if response['Time Series (Daily)'].get(str(date1)) is not None:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "180", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "181", "score": 88, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24) ', '[]', 'aapl(volume, 2018-11-24, 2018-11-24) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "183", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 103, in <module>\n    print(chercher_valeur(DATE_DEBUT, DATE_FIN, data))\n  File \"projet1.py\", line 93, in chercher_valeur\n    infos_date_courante = response['Time Series (Daily)'].get(str(date_courante), False)\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "185", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}]