    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-11-29, 2018-11-29)\n[]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-11-29, 2018-11-29)\n[('2018-11-29', '1081.9325')]\n</pre>
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 39, in <module>\n    d = datetime.date(int(args.debut))\nValueError: invalid literal for int() with base 10: '2018-07-24'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 64, in <module>\n    for i in RESPONSE['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 83, in <module>\n    recup_dico(ARGS.symbole, VALEUR_DEBUT, VALEUR_FIN, ARGS.valeur)\n  File \"projet1.py\", line 60, in recup_dico\n    response = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 94, in <module>\n    a = response['Time Series (Daily)'][args.d]['4. close']\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 121, in <module>\n    main()\n  File \"projet1.py\", line 89, in main\n    liste_empty.append((str(i), s['Time Series (Daily)'][str(i)][\"4. close\"]))\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    DONNEES = AlphaVantageAPI.telecharger_donnees(sym, DEB_A_AJD)\n  File \"/mnt/Documents/Projets/Laval/TA/Partie7/unbundled/bundle-201-13.hg/AlphaVantageAPI.py\", line 28, in telecharger_donnees\n    return response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 128, in <module>\n    generer_liste_valeurs()\n  File \"projet1.py\", line 95, in generer_liste_valeurs\n    liste3.append((str(k), sy['Time Series (Daily)'][str(k)][\"4. close\"]))\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 76, in <module>\n    liste_reponse.append((response['Time Series (Daily)'][j])[cle_valeur(ARGS.valeur)])\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 94, in <module>\n    action(DATE_INITIALE, DATE_FINALE, SYMBOL)\n  File \"projet1.py\", line 70, in action\n    if str(date_sauce) in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3>
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"Projet1.py\", line 80, in <module>\n    display(args)\n  File \"Projet1.py\", line 50, in display\n    for value in response['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 44, in <module>\n    parse_valeur()\n  File \"projet1.py\", line 19, in parse_valeur\n    default='Help', help='show this help message and exit'\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1367, in add_argument\n    return self._add_action(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1730, in _add_action\n    self._optionals._add_action(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1571, in _add_action\n    action = super(_ArgumentGroup, self)._add_action(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1381, in _add_action\n    self._check_conflict(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1520, in _check_conflict\n    conflict_handler(action, confl_optionals)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1529, in _handle_conflict_error\n    raise ArgumentError(action, message % conflict_string)\nargparse.ArgumentError: argument -h: conflicting option string: -h\n</pre>\n
    <h3>R\u00e9sultat crit\u00e8re 3</h3>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>-d=2018-07-24 -f=2018-09-24 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-07-24, 2018-09-24)\n[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-07-24, 2018-09-24)\n('2018-07-24', '1248.0800')\n</pre>
    <h3>R\u00e9sultat crit\u00e8re 3</h3>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-11-29, 2018-11-29)\n[('2018-11-29', '1084.9995')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-11-29, 2018-11-29)\n[]\n</pre>
