[{"\u00e9quipe": "020", "score": 50, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[(2018-07-24, 1248.0800), (2018-09-24, 1173.3700)]']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 77, in <module>\n    format_final(ARGS.symbole)\n  File \"projet1.py\", line 74, in format_final\n    premiere_ligne(k[symb])\n  File \"projet1.py\", line 24, in premiere_ligne\n    a = datetime.datetime.strptime(ARGS.fin, \"%Y-%m-%d\")\nTypeError: strptime() argument 1 must be str, not None\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 77, in <module>\n    format_final(ARGS.symbole)\n  File \"projet1.py\", line 74, in format_final\n    premiere_ligne(k[symb])\n  File \"projet1.py\", line 24, in premiere_ligne\n    a = datetime.datetime.strptime(ARGS.fin, \"%Y-%m-%d\")\nTypeError: strptime() argument 1 must be str, not None\n\n\n</pre>"}, {"\u00e9quipe": "038", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "001", "score": 98, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "003", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "004", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "006", "score": 70, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-07-25, 2018-07-26, 2018-07-27, 2018-07-30, 2018-07-31, 2018-08-01, 2018-08-02, 2018-08-03, 2018-08-06, 2018-08-07, 2018-08-08, 2018-08-09, 2018-08-10, 2018-08-13, 2018-08-14, 2018-08-15, 2018-08-16, 2018-08-17, 2018-08-20, 2018-08-21, 2018-08-22, 2018-08-23, 2018-08-24, 2018-08-27, 2018-08-28, 2018-08-29, 2018-08-30, 2018-08-31, 2018-09-04, 2018-09-05, 2018-09-06, 2018-09-07, 2018-09-10, 2018-09-11, 2018-09-12, 2018-09-13, 2018-09-14, 2018-09-17, 2018-09-18, 2018-09-19, 2018-09-20, 2018-09-21, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    for i in range(0, len(args.DATE)):\nTypeError: object of type 'NoneType' has no len()\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    for i in range(0, len(args.DATE)):\nTypeError: object of type 'NoneType' has no len()\n\n\n</pre>"}, {"\u00e9quipe": "007", "score": 70, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 98, in <module>\n    print(valeur_desiree(valeur))\n  File \"projet1.py\", line 85, in valeur_desiree\n    tupl = tuple((fin, str(response[\"Time Series (Daily)\"][fin][dico[valeur]])))\nKeyError: '2018-11-24'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f FIN]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f FIN]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol\nprojet1.py: error: unrecognized arguments: aapl\n\n\n</pre>"}, {"\u00e9quipe": "008", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "009", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "011", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "012", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "013", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "014", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "015", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 102, in <module>\n    valeur1 = dureeplusgrande()['Time Series (Daily)']['{}'.format(dated)][clef]\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 99, in <module>\n    valeur1 = dureepluspetite()['Time Series (Daily)']['{}'.format(dated)][clef]\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --valeur=volume\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 99, in <module>\n    valeur1 = dureepluspetite()['Time Series (Daily)']['{}'.format(dated)][clef]\nKeyError: '2018-11-24'\n\n\n</pre>"}, {"\u00e9quipe": "016", "score": 68, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-07-24, 2018-09-24)\", 'Le symbole goog est indisponible.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, None, None)\", 'Le symbole goog est indisponible.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](volume, 2018-09-21, 2018-09-24)\", 'Le symbole goog est indisponible.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog', 'aapl'](volume, None, None)\", 'Le symbole goog est indisponible.', 'Le symbole aapl est indisponible.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "017", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "018", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "019", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "021", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "022", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "023", "score": 68, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"Le symbole entr\u00e9 n'existe pas\", 'goog(fermeture, 2018-07-24, 2018-09-24)']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"Aucune date de d\u00e9but entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Aucune date de fin entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Le symbole entr\u00e9 n'existe pas\", 'goog(fermeture, 2018-11-24, 2018-11-24)']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"Le symbole entr\u00e9 n'existe pas\", 'goog(volume, 2018-09-21, 2018-09-24)']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"Aucune date de d\u00e9but entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Aucune date de fin entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Le symbole entr\u00e9 n'existe pas\", 'goog(volume, 2018-11-24, 2018-11-24)', \"Le symbole entr\u00e9 n'existe pas\", 'aapl(volume, 2018-11-24, 2018-11-24)']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "024", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "025", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "026", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "027", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "029", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "029", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "030", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "030", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "031", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "032", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "033", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "035", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "036", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "039", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}]