[{"\u00e9quipe": "120", "score": 70, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>-d=2018-07-24 -f=2018-09-24 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-07-24, 2018-09-24)\n[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>[]\n</pre><p>Votre erreur est : </p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 127, in <module>\n    chercherdansledictionnaire()\n  File \"projet1.py\", line 92, in chercherdansledictionnaire\n    listefinale.append((str(i), ss['Time Series (Daily)'][str(i)][\"4. close\"]))\nKeyError: '2018-09-03'\n</pre>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>-f=2018-09-24 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-09-24, 2018-09-24)\n[('2018-09-24', '1173.3700')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>[]\n</pre><p>Votre erreur est : </p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 127, in <module>\n    chercherdansledictionnaire()\n  File \"projet1.py\", line 84, in chercherdansledictionnaire\n    intervalle = longueurentredate()\n  File \"projet1.py\", line 72, in longueurentredate\n    dates = transformation()\n  File \"projet1.py\", line 67, in transformation\n    start = date(int(deb[0]), int(deb[1]), int(deb[2]))\nValueError: invalid literal for int() with base 10: 'date_fin'\n</pre>"}, {"\u00e9quipe": "122", "score": 100, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo, vous avez pass\u00e9 tout les tests.</p>"}, {"\u00e9quipe": "123", "score": 62, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3>\n<p>Vous avez \u00e9chou\u00e9 le test de fonctionnement : <CODE>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(volume, 2018-09-21, 2018-09-24)\n[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>goog(volume, 2018-09-21, 2018-09-24)\n[('2018-09-21, '4405584')], ('2018-09-24, '1271017')]\n</pre>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>-d=2018-07-24 -f=2018-09-24 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-07-24, 2018-09-24)\n[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-07-24, 2018-09-24)\n[('2018-07-24, '1248.0800')], ('2018-09-24, '1173.3700')]\n</pre>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>-f=2018-09-24 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-09-24, 2018-09-24)\n[('2018-09-24', '1173.3700')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>goog(fermeture, 2018-09-24, 2018-09-24)\n[('2018-09-24, '1173.3700')]\n</pre>\n<p>Vous avez \u00e9chou\u00e9 le test : <CODE>--valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\n</CODE></p>\n<p>La bonne r\u00e9ponse est : </p>\n<pre>goog(volume, 2018-09-21, 2018-09-24)\n[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\n</pre>\n<p>Votre r\u00e9ponse est : </p>\n<pre>[]\n</pre><p>Votre erreur est : </p>\n<pre> usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n</pre>"}, {"\u00e9quipe": "124", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"Projet1.py\", line 8, in <module>\n    import numpy\nModuleNotFoundError: No module named 'numpy'\n</pre>\n"}, {"\u00e9quipe": "125", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 93, in <module>\n    OUT.append((PRM.debut, ANS['Time Series (Daily)'][PRM.debut][VAL[PRM.valeur]]))\nKeyError: '2018-009-21'\n</pre>\n"}, {"\u00e9quipe": "126", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connection.py\", line 171, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/util/connection.py\", line 56, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/socket.py\", line 748, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -2] Name or service not known\n</pre>\n"}, {"\u00e9quipe": "127", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "128", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 48, in <module>\n    new_dict = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "129", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}]