[
    {
        "\u00e9quipe": "114",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 106, in <module>\n    val = response[\"Time Series (Daily)\"][j][type_val]\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "115",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"
    },
    {
        "\u00e9quipe": "118",
        "score": 85,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo vous avez pass\u00e9 tout les tests.</p>"
    },
    {
        "\u00e9quipe": "119",
        "score": 60,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo vous avez pass\u00e9 tout les tests.</p>"
    },
    {
        "\u00e9quipe": "120",
        "score": 60,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo vous avez pass\u00e9 tout les tests.</p>"
    },
    {
        "\u00e9quipe": "122",
        "score": 60,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo vous avez pass\u00e9 tout les tests.</p>"
    },
    {
        "\u00e9quipe": "123",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 53, in <module>\n    ouvdeb = response['Time Series (Daily)'][debut]['1. open']\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "124",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"Projet1.py\", line 8, in <module>\n    import numpy\nModuleNotFoundError: No module named 'numpy'\n</pre>\n"
    },
    {
        "\u00e9quipe": "125",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 93, in <module>\n    OUT.append((PRM.debut, ANS['Time Series (Daily)'][PRM.debut][VAL[PRM.valeur]]))\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "126",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connection.py\", line 171, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/util/connection.py\", line 56, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/socket.py\", line 748, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -2] Name or service not known\n</pre>\n"
    },
    {
        "\u00e9quipe": "127",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"
    },
    {
        "\u00e9quipe": "128",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 48, in <module>\n    new_dict = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "129",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"
    },
    {
        "\u00e9quipe": "130",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> usage: projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v  {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: -v=volume\n</pre>\n"
    },
    {
        "\u00e9quipe": "131",
        "score": 75,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo vous avez pass\u00e9 tout les tests.</p>"
    },
    {
        "\u00e9quipe": "132",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 93, in <module>\n    dictio = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "133",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 99, in <module>\n    temp = response[\"Time Series (Daily)\"][i][KeyValeur[args.valeur]]\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "134",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"Projet1.py\", line 107, in <module>\n    dico_TSD = response['Time Series (Daily)']  # dico_TSD est le dictionnaire obtenu\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "135",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"
    },
    {
        "\u00e9quipe": "136",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 52, in <module>\n    print(format(args))\n  File \"projet1.py\", line 47, in format\n    a = response['Time Series (Daily)'][date_generated]\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "137",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>-v=volume -d=2018-09-21 -f=2018-09-24 goog\n</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"
    },
    {
        "\u00e9quipe": "139",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"
    },
    {
        "\u00e9quipe": "140",
        "score": 90,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Bravo vous avez pass\u00e9 tout les tests.</p>"
    },
    {
        "\u00e9quipe": "141",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 76, in <module>\n    response = json.loads((requests.get(url=url, params=params)).text)['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    },
    {
        "\u00e9quipe": "142",
        "score": 0,
        "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 107, in <module>\n    affichage(K, ARGS.valeur, ARGS.debut, ARGS.fin, FORMAT)\n  File \"projet1.py\", line 49, in affichage\n    print(formatage(extraction(symbole, typeformat), debut, fin, valeur))\n  File \"projet1.py\", line 30, in formatage\n    for k in bourse['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n</pre>\n"
    }
]
